//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34011
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// Nom du fichier d'origine :
// Date de génération : 22/03/2014 01:09:29
namespace LearningCompany_WP.AccesCommerciaux
{
    
    /// <summary>
    /// Il n'existe aucun commentaire pour LearningCompanyContext dans le schéma.
    /// </summary>
    public partial class LearningCompanyContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialisez un nouvel objet LearningCompanyContext.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public LearningCompanyContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Étant donné que l'espace de noms configuré pour cette référence de service
        /// dans Visual Studio est différent de celui indiqué dans le
        /// schéma du serveur, utilisez des mappeurs de type pour effectuer des mappages entre les deux.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LearningCompany.Entities", "LearningCompany_WP.AccesCommerciaux");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Étant donné que l'espace de noms configuré pour cette référence de service
        /// dans Visual Studio est différent de celui indiqué dans le
        /// schéma du serveur, utilisez des mappeurs de type pour effectuer des mappages entre les deux.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LearningCompany_WP.AccesCommerciaux", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LearningCompany.Entities.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Civilites dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Civilite> Civilites
        {
            get
            {
                if ((this._Civilites == null))
                {
                    this._Civilites = base.CreateQuery<Civilite>("Civilites");
                }
                return this._Civilites;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Civilite> _Civilites;
        /// <summary>
        /// Il n'existe aucun commentaire pour Clients dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Client> Clients
        {
            get
            {
                if ((this._Clients == null))
                {
                    this._Clients = base.CreateQuery<Client>("Clients");
                }
                return this._Clients;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Client> _Clients;
        /// <summary>
        /// Il n'existe aucun commentaire pour Formateurs dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Formateur> Formateurs
        {
            get
            {
                if ((this._Formateurs == null))
                {
                    this._Formateurs = base.CreateQuery<Formateur>("Formateurs");
                }
                return this._Formateurs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Formateur> _Formateurs;
        /// <summary>
        /// Il n'existe aucun commentaire pour Stagiaires dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Stagiaire> Stagiaires
        {
            get
            {
                if ((this._Stagiaires == null))
                {
                    this._Stagiaires = base.CreateQuery<Stagiaire>("Stagiaires");
                }
                return this._Stagiaires;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Stagiaire> _Stagiaires;
        /// <summary>
        /// Il n'existe aucun commentaire pour Civilites dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCivilites(Civilite civilite)
        {
            base.AddObject("Civilites", civilite);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Clients dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToClients(Client client)
        {
            base.AddObject("Clients", client);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Formateurs dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFormateurs(Formateur formateur)
        {
            base.AddObject("Formateurs", formateur);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Stagiaires dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStagiaires(Stagiaire stagiaire)
        {
            base.AddObject("Stagiaires", stagiaire);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"LearningCompany.Entities\" xmlns=\"http://schemas.microsoft.com/ado/200" +
                "9/11/edm\"><EntityType Name=\"Civilite\"><Key><PropertyRef Name=\"CiviliteID\" /></Ke" +
                "y><Property Name=\"CiviliteID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name" +
                "=\"LibelleCourt\" Type=\"Edm.String\" /><Property Name=\"LibelleLong\" Type=\"Edm.Strin" +
                "g\" /><NavigationProperty Name=\"Formateurs\" Relationship=\"LearningCompany.Entitie" +
                "s.Civilite_Formateurs_Formateur_Civilite\" ToRole=\"Formateur_Civilite\" FromRole=\"" +
                "Civilite_Formateurs\" /><NavigationProperty Name=\"Stagiaires\" Relationship=\"Learn" +
                "ingCompany.Entities.Civilite_Stagiaires_Stagiaire_Civilite\" ToRole=\"Stagiaire_Ci" +
                "vilite\" FromRole=\"Civilite_Stagiaires\" /></EntityType><EntityType Name=\"Client\">" +
                "<Key><PropertyRef Name=\"ClientID\" /></Key><Property Name=\"ClientID\" Type=\"Edm.In" +
                "t32\" Nullable=\"false\" /><Property Name=\"Reference\" Type=\"Edm.String\" /><Property" +
                " Name=\"RaisonSociale\" Type=\"Edm.String\" /><Property Name=\"Adresse\" Type=\"Edm.Str" +
                "ing\" /><Property Name=\"CodePostal\" Type=\"Edm.String\" /><Property Name=\"Ville\" Ty" +
                "pe=\"Edm.String\" /><Property Name=\"Telephone\" Type=\"Edm.String\" /><Property Name=" +
                "\"Courriel\" Type=\"Edm.String\" /><Property Name=\"UrlSite\" Type=\"Edm.String\" /><Pro" +
                "perty Name=\"MotDePasse\" Type=\"Edm.String\" /><Property Name=\"SecteurActiviteID\" T" +
                "ype=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"CommercialID\" Type=\"Edm.Int32" +
                "\" Nullable=\"false\" /><NavigationProperty Name=\"Stagiaires\" Relationship=\"Learnin" +
                "gCompany.Entities.Client_Stagiaires_Stagiaire_Client\" ToRole=\"Stagiaire_Client\" " +
                "FromRole=\"Client_Stagiaires\" /></EntityType><EntityType Name=\"Formateur\"><Key><P" +
                "ropertyRef Name=\"FormateurID\" /></Key><Property Name=\"FormateurID\" Type=\"Edm.Int" +
                "32\" Nullable=\"false\" /><Property Name=\"Nom\" Type=\"Edm.String\" /><Property Name=\"" +
                "Prenom\" Type=\"Edm.String\" /><Property Name=\"UrlPhoto\" Type=\"Edm.String\" /><Prope" +
                "rty Name=\"Courriel\" Type=\"Edm.String\" /><Property Name=\"Telephone\" Type=\"Edm.Str" +
                "ing\" /><Property Name=\"IntervenantExterieur\" Type=\"Edm.Boolean\" Nullable=\"false\"" +
                " /><Property Name=\"Infos\" Type=\"Edm.String\" /><Property Name=\"CiviliteID\" Type=\"" +
                "Edm.Int32\" Nullable=\"false\" /><NavigationProperty Name=\"Civilite\" Relationship=\"" +
                "LearningCompany.Entities.Civilite_Formateurs_Formateur_Civilite\" ToRole=\"Civilit" +
                "e_Formateurs\" FromRole=\"Formateur_Civilite\" /></EntityType><EntityType Name=\"Sta" +
                "giaire\"><Key><PropertyRef Name=\"StagiaireID\" /></Key><Property Name=\"StagiaireID" +
                "\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Nom\" Type=\"Edm.String\" /><" +
                "Property Name=\"Prenom\" Type=\"Edm.String\" /><Property Name=\"Courriel\" Type=\"Edm.S" +
                "tring\" /><Property Name=\"CiviliteID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Proper" +
                "ty Name=\"ClientID\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationProperty Name=" +
                "\"Civilite\" Relationship=\"LearningCompany.Entities.Civilite_Stagiaires_Stagiaire_" +
                "Civilite\" ToRole=\"Civilite_Stagiaires\" FromRole=\"Stagiaire_Civilite\" /><Navigati" +
                "onProperty Name=\"Client\" Relationship=\"LearningCompany.Entities.Client_Stagiaire" +
                "s_Stagiaire_Client\" ToRole=\"Client_Stagiaires\" FromRole=\"Stagiaire_Client\" /></E" +
                "ntityType><Association Name=\"Civilite_Formateurs_Formateur_Civilite\"><End Type=\"" +
                "LearningCompany.Entities.Formateur\" Role=\"Formateur_Civilite\" Multiplicity=\"*\" /" +
                "><End Type=\"LearningCompany.Entities.Civilite\" Role=\"Civilite_Formateurs\" Multip" +
                "licity=\"0..1\" /></Association><Association Name=\"Civilite_Stagiaires_Stagiaire_C" +
                "ivilite\"><End Type=\"LearningCompany.Entities.Stagiaire\" Role=\"Stagiaire_Civilite" +
                "\" Multiplicity=\"*\" /><End Type=\"LearningCompany.Entities.Civilite\" Role=\"Civilit" +
                "e_Stagiaires\" Multiplicity=\"0..1\" /></Association><Association Name=\"Client_Stag" +
                "iaires_Stagiaire_Client\"><End Type=\"LearningCompany.Entities.Stagiaire\" Role=\"St" +
                "agiaire_Client\" Multiplicity=\"*\" /><End Type=\"LearningCompany.Entities.Client\" R" +
                "ole=\"Client_Stagiaires\" Multiplicity=\"0..1\" /></Association><EntityContainer Nam" +
                "e=\"LearningCompanyContext\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Ci" +
                "vilites\" EntityType=\"LearningCompany.Entities.Civilite\" /><EntitySet Name=\"Clien" +
                "ts\" EntityType=\"LearningCompany.Entities.Client\" /><EntitySet Name=\"Formateurs\" " +
                "EntityType=\"LearningCompany.Entities.Formateur\" /><EntitySet Name=\"Stagiaires\" E" +
                "ntityType=\"LearningCompany.Entities.Stagiaire\" /><AssociationSet Name=\"Formateur" +
                "_Civilite\" Association=\"LearningCompany.Entities.Civilite_Formateurs_Formateur_C" +
                "ivilite\"><End Role=\"Civilite_Formateurs\" EntitySet=\"Civilites\" /><End Role=\"Form" +
                "ateur_Civilite\" EntitySet=\"Formateurs\" /></AssociationSet><AssociationSet Name=\"" +
                "Stagiaire_Civilite\" Association=\"LearningCompany.Entities.Civilite_Stagiaires_St" +
                "agiaire_Civilite\"><End Role=\"Civilite_Stagiaires\" EntitySet=\"Civilites\" /><End R" +
                "ole=\"Stagiaire_Civilite\" EntitySet=\"Stagiaires\" /></AssociationSet><AssociationS" +
                "et Name=\"Stagiaire_Client\" Association=\"LearningCompany.Entities.Client_Stagiair" +
                "es_Stagiaire_Client\"><End Role=\"Client_Stagiaires\" EntitySet=\"Clients\" /><End Ro" +
                "le=\"Stagiaire_Client\" EntitySet=\"Stagiaires\" /></AssociationSet></EntityContaine" +
                "r></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour LearningCompany.Entities.Civilite dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// CiviliteID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Civilites")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CiviliteID")]
    public partial class Civilite : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet Civilite.
        /// </summary>
        /// <param name="civiliteID">Valeur initiale de CiviliteID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Civilite CreateCivilite(int civiliteID)
        {
            Civilite civilite = new Civilite();
            civilite.CiviliteID = civiliteID;
            return civilite;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété CiviliteID dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CiviliteID
        {
            get
            {
                return this._CiviliteID;
            }
            set
            {
                this.OnCiviliteIDChanging(value);
                this._CiviliteID = value;
                this.OnCiviliteIDChanged();
                this.OnPropertyChanged("CiviliteID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CiviliteID;
        partial void OnCiviliteIDChanging(int value);
        partial void OnCiviliteIDChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété LibelleCourt dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LibelleCourt
        {
            get
            {
                return this._LibelleCourt;
            }
            set
            {
                this.OnLibelleCourtChanging(value);
                this._LibelleCourt = value;
                this.OnLibelleCourtChanged();
                this.OnPropertyChanged("LibelleCourt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LibelleCourt;
        partial void OnLibelleCourtChanging(string value);
        partial void OnLibelleCourtChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété LibelleLong dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LibelleLong
        {
            get
            {
                return this._LibelleLong;
            }
            set
            {
                this.OnLibelleLongChanging(value);
                this._LibelleLong = value;
                this.OnLibelleLongChanged();
                this.OnPropertyChanged("LibelleLong");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LibelleLong;
        partial void OnLibelleLongChanging(string value);
        partial void OnLibelleLongChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Formateurs dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Formateur> Formateurs
        {
            get
            {
                return this._Formateurs;
            }
            set
            {
                this._Formateurs = value;
                this.OnPropertyChanged("Formateurs");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Formateur> _Formateurs = new global::System.Data.Services.Client.DataServiceCollection<Formateur>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Il n'existe aucun commentaire pour Stagiaires dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Stagiaire> Stagiaires
        {
            get
            {
                return this._Stagiaires;
            }
            set
            {
                this._Stagiaires = value;
                this.OnPropertyChanged("Stagiaires");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Stagiaire> _Stagiaires = new global::System.Data.Services.Client.DataServiceCollection<Stagiaire>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour LearningCompany.Entities.Client dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// ClientID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Clients")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ClientID")]
    public partial class Client : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet Client.
        /// </summary>
        /// <param name="clientID">Valeur initiale de ClientID.</param>
        /// <param name="secteurActiviteID">Valeur initiale de SecteurActiviteID.</param>
        /// <param name="commercialID">Valeur initiale de CommercialID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Client CreateClient(int clientID, int secteurActiviteID, int commercialID)
        {
            Client client = new Client();
            client.ClientID = clientID;
            client.SecteurActiviteID = secteurActiviteID;
            client.CommercialID = commercialID;
            return client;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété ClientID dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ClientID
        {
            get
            {
                return this._ClientID;
            }
            set
            {
                this.OnClientIDChanging(value);
                this._ClientID = value;
                this.OnClientIDChanged();
                this.OnPropertyChanged("ClientID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ClientID;
        partial void OnClientIDChanging(int value);
        partial void OnClientIDChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Reference dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Reference
        {
            get
            {
                return this._Reference;
            }
            set
            {
                this.OnReferenceChanging(value);
                this._Reference = value;
                this.OnReferenceChanged();
                this.OnPropertyChanged("Reference");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Reference;
        partial void OnReferenceChanging(string value);
        partial void OnReferenceChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété RaisonSociale dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RaisonSociale
        {
            get
            {
                return this._RaisonSociale;
            }
            set
            {
                this.OnRaisonSocialeChanging(value);
                this._RaisonSociale = value;
                this.OnRaisonSocialeChanged();
                this.OnPropertyChanged("RaisonSociale");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RaisonSociale;
        partial void OnRaisonSocialeChanging(string value);
        partial void OnRaisonSocialeChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Adresse dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Adresse
        {
            get
            {
                return this._Adresse;
            }
            set
            {
                this.OnAdresseChanging(value);
                this._Adresse = value;
                this.OnAdresseChanged();
                this.OnPropertyChanged("Adresse");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Adresse;
        partial void OnAdresseChanging(string value);
        partial void OnAdresseChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété CodePostal dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CodePostal
        {
            get
            {
                return this._CodePostal;
            }
            set
            {
                this.OnCodePostalChanging(value);
                this._CodePostal = value;
                this.OnCodePostalChanged();
                this.OnPropertyChanged("CodePostal");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CodePostal;
        partial void OnCodePostalChanging(string value);
        partial void OnCodePostalChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Ville dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ville
        {
            get
            {
                return this._Ville;
            }
            set
            {
                this.OnVilleChanging(value);
                this._Ville = value;
                this.OnVilleChanged();
                this.OnPropertyChanged("Ville");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ville;
        partial void OnVilleChanging(string value);
        partial void OnVilleChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Telephone dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Telephone
        {
            get
            {
                return this._Telephone;
            }
            set
            {
                this.OnTelephoneChanging(value);
                this._Telephone = value;
                this.OnTelephoneChanged();
                this.OnPropertyChanged("Telephone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Telephone;
        partial void OnTelephoneChanging(string value);
        partial void OnTelephoneChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Courriel dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Courriel
        {
            get
            {
                return this._Courriel;
            }
            set
            {
                this.OnCourrielChanging(value);
                this._Courriel = value;
                this.OnCourrielChanged();
                this.OnPropertyChanged("Courriel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Courriel;
        partial void OnCourrielChanging(string value);
        partial void OnCourrielChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété UrlSite dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UrlSite
        {
            get
            {
                return this._UrlSite;
            }
            set
            {
                this.OnUrlSiteChanging(value);
                this._UrlSite = value;
                this.OnUrlSiteChanged();
                this.OnPropertyChanged("UrlSite");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UrlSite;
        partial void OnUrlSiteChanging(string value);
        partial void OnUrlSiteChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété MotDePasse dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MotDePasse
        {
            get
            {
                return this._MotDePasse;
            }
            set
            {
                this.OnMotDePasseChanging(value);
                this._MotDePasse = value;
                this.OnMotDePasseChanged();
                this.OnPropertyChanged("MotDePasse");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MotDePasse;
        partial void OnMotDePasseChanging(string value);
        partial void OnMotDePasseChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété SecteurActiviteID dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SecteurActiviteID
        {
            get
            {
                return this._SecteurActiviteID;
            }
            set
            {
                this.OnSecteurActiviteIDChanging(value);
                this._SecteurActiviteID = value;
                this.OnSecteurActiviteIDChanged();
                this.OnPropertyChanged("SecteurActiviteID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SecteurActiviteID;
        partial void OnSecteurActiviteIDChanging(int value);
        partial void OnSecteurActiviteIDChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété CommercialID dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CommercialID
        {
            get
            {
                return this._CommercialID;
            }
            set
            {
                this.OnCommercialIDChanging(value);
                this._CommercialID = value;
                this.OnCommercialIDChanged();
                this.OnPropertyChanged("CommercialID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CommercialID;
        partial void OnCommercialIDChanging(int value);
        partial void OnCommercialIDChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Stagiaires dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Stagiaire> Stagiaires
        {
            get
            {
                return this._Stagiaires;
            }
            set
            {
                this._Stagiaires = value;
                this.OnPropertyChanged("Stagiaires");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Stagiaire> _Stagiaires = new global::System.Data.Services.Client.DataServiceCollection<Stagiaire>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour LearningCompany.Entities.Formateur dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// FormateurID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Formateurs")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("FormateurID")]
    public partial class Formateur : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet Formateur.
        /// </summary>
        /// <param name="formateurID">Valeur initiale de FormateurID.</param>
        /// <param name="intervenantExterieur">Valeur initiale de IntervenantExterieur.</param>
        /// <param name="civiliteID">Valeur initiale de CiviliteID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Formateur CreateFormateur(int formateurID, bool intervenantExterieur, int civiliteID)
        {
            Formateur formateur = new Formateur();
            formateur.FormateurID = formateurID;
            formateur.IntervenantExterieur = intervenantExterieur;
            formateur.CiviliteID = civiliteID;
            return formateur;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété FormateurID dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int FormateurID
        {
            get
            {
                return this._FormateurID;
            }
            set
            {
                this.OnFormateurIDChanging(value);
                this._FormateurID = value;
                this.OnFormateurIDChanged();
                this.OnPropertyChanged("FormateurID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _FormateurID;
        partial void OnFormateurIDChanging(int value);
        partial void OnFormateurIDChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Nom dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nom
        {
            get
            {
                return this._Nom;
            }
            set
            {
                this.OnNomChanging(value);
                this._Nom = value;
                this.OnNomChanged();
                this.OnPropertyChanged("Nom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nom;
        partial void OnNomChanging(string value);
        partial void OnNomChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Prenom dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Prenom
        {
            get
            {
                return this._Prenom;
            }
            set
            {
                this.OnPrenomChanging(value);
                this._Prenom = value;
                this.OnPrenomChanged();
                this.OnPropertyChanged("Prenom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Prenom;
        partial void OnPrenomChanging(string value);
        partial void OnPrenomChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété UrlPhoto dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UrlPhoto
        {
            get
            {
                return this._UrlPhoto;
            }
            set
            {
                this.OnUrlPhotoChanging(value);
                this._UrlPhoto = value;
                this.OnUrlPhotoChanged();
                this.OnPropertyChanged("UrlPhoto");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UrlPhoto;
        partial void OnUrlPhotoChanging(string value);
        partial void OnUrlPhotoChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Courriel dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Courriel
        {
            get
            {
                return this._Courriel;
            }
            set
            {
                this.OnCourrielChanging(value);
                this._Courriel = value;
                this.OnCourrielChanged();
                this.OnPropertyChanged("Courriel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Courriel;
        partial void OnCourrielChanging(string value);
        partial void OnCourrielChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Telephone dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Telephone
        {
            get
            {
                return this._Telephone;
            }
            set
            {
                this.OnTelephoneChanging(value);
                this._Telephone = value;
                this.OnTelephoneChanged();
                this.OnPropertyChanged("Telephone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Telephone;
        partial void OnTelephoneChanging(string value);
        partial void OnTelephoneChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété IntervenantExterieur dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IntervenantExterieur
        {
            get
            {
                return this._IntervenantExterieur;
            }
            set
            {
                this.OnIntervenantExterieurChanging(value);
                this._IntervenantExterieur = value;
                this.OnIntervenantExterieurChanged();
                this.OnPropertyChanged("IntervenantExterieur");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IntervenantExterieur;
        partial void OnIntervenantExterieurChanging(bool value);
        partial void OnIntervenantExterieurChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Infos dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Infos
        {
            get
            {
                return this._Infos;
            }
            set
            {
                this.OnInfosChanging(value);
                this._Infos = value;
                this.OnInfosChanged();
                this.OnPropertyChanged("Infos");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Infos;
        partial void OnInfosChanging(string value);
        partial void OnInfosChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété CiviliteID dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CiviliteID
        {
            get
            {
                return this._CiviliteID;
            }
            set
            {
                this.OnCiviliteIDChanging(value);
                this._CiviliteID = value;
                this.OnCiviliteIDChanged();
                this.OnPropertyChanged("CiviliteID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CiviliteID;
        partial void OnCiviliteIDChanging(int value);
        partial void OnCiviliteIDChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Civilite dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Civilite Civilite
        {
            get
            {
                return this._Civilite;
            }
            set
            {
                this._Civilite = value;
                this.OnPropertyChanged("Civilite");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Civilite _Civilite;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour LearningCompany.Entities.Stagiaire dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// StagiaireID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Stagiaires")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("StagiaireID")]
    public partial class Stagiaire : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet Stagiaire.
        /// </summary>
        /// <param name="stagiaireID">Valeur initiale de StagiaireID.</param>
        /// <param name="civiliteID">Valeur initiale de CiviliteID.</param>
        /// <param name="clientID">Valeur initiale de ClientID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Stagiaire CreateStagiaire(int stagiaireID, int civiliteID, int clientID)
        {
            Stagiaire stagiaire = new Stagiaire();
            stagiaire.StagiaireID = stagiaireID;
            stagiaire.CiviliteID = civiliteID;
            stagiaire.ClientID = clientID;
            return stagiaire;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété StagiaireID dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int StagiaireID
        {
            get
            {
                return this._StagiaireID;
            }
            set
            {
                this.OnStagiaireIDChanging(value);
                this._StagiaireID = value;
                this.OnStagiaireIDChanged();
                this.OnPropertyChanged("StagiaireID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _StagiaireID;
        partial void OnStagiaireIDChanging(int value);
        partial void OnStagiaireIDChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Nom dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nom
        {
            get
            {
                return this._Nom;
            }
            set
            {
                this.OnNomChanging(value);
                this._Nom = value;
                this.OnNomChanged();
                this.OnPropertyChanged("Nom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nom;
        partial void OnNomChanging(string value);
        partial void OnNomChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Prenom dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Prenom
        {
            get
            {
                return this._Prenom;
            }
            set
            {
                this.OnPrenomChanging(value);
                this._Prenom = value;
                this.OnPrenomChanged();
                this.OnPropertyChanged("Prenom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Prenom;
        partial void OnPrenomChanging(string value);
        partial void OnPrenomChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Courriel dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Courriel
        {
            get
            {
                return this._Courriel;
            }
            set
            {
                this.OnCourrielChanging(value);
                this._Courriel = value;
                this.OnCourrielChanged();
                this.OnPropertyChanged("Courriel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Courriel;
        partial void OnCourrielChanging(string value);
        partial void OnCourrielChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété CiviliteID dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CiviliteID
        {
            get
            {
                return this._CiviliteID;
            }
            set
            {
                this.OnCiviliteIDChanging(value);
                this._CiviliteID = value;
                this.OnCiviliteIDChanged();
                this.OnPropertyChanged("CiviliteID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CiviliteID;
        partial void OnCiviliteIDChanging(int value);
        partial void OnCiviliteIDChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété ClientID dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ClientID
        {
            get
            {
                return this._ClientID;
            }
            set
            {
                this.OnClientIDChanging(value);
                this._ClientID = value;
                this.OnClientIDChanged();
                this.OnPropertyChanged("ClientID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ClientID;
        partial void OnClientIDChanging(int value);
        partial void OnClientIDChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Civilite dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Civilite Civilite
        {
            get
            {
                return this._Civilite;
            }
            set
            {
                this._Civilite = value;
                this.OnPropertyChanged("Civilite");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Civilite _Civilite;
        /// <summary>
        /// Il n'existe aucun commentaire pour Client dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Client Client
        {
            get
            {
                return this._Client;
            }
            set
            {
                this._Client = value;
                this.OnPropertyChanged("Client");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Client _Client;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
